src/forj/urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static


urlpatterns = []

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/forj/web/admin/urls.py
from django.conf.urls import url
from django.contrib import admin

from forj.urls import urlpatterns


urlpatterns = urlpatterns + [url(r"^", admin.site.urls)]

src/forj/web/frontend/urls.py
from django.urls import re_path as url
from django.views import generic

from . import views

from forj.urls import urlpatterns


urlpatterns = urlpatterns + [
    url(
        r"^sitemap-arbo.xml$",
        generic.TemplateView.as_view(
            template_name="sitemap-arbo.html", content_type="text/xml"
        ),
    ),
    url(r"^healthcheck/$", views.healthcheck, name="healthcheck"),
    url(r"^$", views.home, name="home"),
    url(
        r"^checkout/(?:(?P<reference>\w+)/)?$",
        views.CheckoutView.as_view(),
        name="checkout",
    ),
    url(
        r"^checkout/(?P<reference>\w+)/payment/$",
        views.PaymentView.as_view(),
        name="payment",
    ),
    url(
        r"^checkout/(?P<reference>\w+)/success/$",
        views.SuccessView.as_view(),
        name="success",
    ),
    url(
        r"^checkout/(?P<reference>\w+)/invoice/$",
        views.InvoiceView.as_view(),
        name="invoice",
    ),
    url(r"^cart/$", views.cart, name="cart"),
    url(r"^handler404/", generic.TemplateView.as_view(template_name="404.html")),
    url(
        r"^terms/",
        generic.TemplateView.as_view(template_name="forj/terms.html"),
        name="terms",
    ),
    url(
        r"^about/",
        generic.TemplateView.as_view(template_name="forj/about.html"),
        name="about",
    ),
    url(r"^handler500/", generic.TemplateView.as_view(template_name="500.html")),
    url(r"^collection/$", views.collection, name="collection"),
    url(
        r"^page/(?P<pk>\d+)/(?P<slug>[\-\w]+)/$",
        views.PageDetailView.as_view(),
        name="page_detail",
    ),
]

src/forj/db/models/base.py
from django.db import models
from django.utils import timezone as datetime


class QuerySet(models.QuerySet):
    pass


class Manager(models.Manager):
    def get_queryset(self):
        return QuerySet(self.model)


class Model(models.Model):
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    objects = Manager()

    class Meta:
        abstract = True

src/forj/models/product.py
from django.db import models
from django.utils.functional import cached_property
from django.conf import settings

from forj.decorators import cache_for_request
from forj.db.models import base
from forj.criteria import CriteriaSet
from forj.db.models.fields import AmountField
from forj import constants, exceptions
from forj.utils.math import expr


class ProductQuerySet(base.QuerySet):
    def from_reference(self, reference):
        for product in self:
            if product.handle_reference(reference):
                return product

        raise exceptions.InvalidProductRef(
            "Product ref {} is not available".format(reference)
        )


class ProductManager(base.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model)

    @cache_for_request
    def cache(self):
        return list(self.order_by("price", "-condition"))

    def cached_from_reference(self, reference):
        products = self.cache()

        for product in products:
            if product.handle_reference(reference):
                return product

        raise exceptions.InvalidProductRef(
            "Product ref {} is not available".format(reference)
        )

    def from_reference(self, reference):
        return self.order_by("price", "-condition").from_reference(reference)


class Product(base.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    reference = models.CharField(
        max_length=100, verbose_name="Reference", db_index=True
    )
    description = models.TextField(null=True, verbose_name="Description", blank=True)
    price = AmountField(verbose_name="Price", null=True, blank=True)
    formula = models.CharField(
        max_length=100, verbose_name="Formula", null=True, blank=True
    )
    condition = models.CharField(
        max_length=100, verbose_name="Condition", null=True, blank=True
    )
    currency = models.CharField(
        max_length=3,
        choices=constants.CURRENCY_CHOICES,
        default=settings.DEFAULT_CURRENCY,
    )
    shipping_cost = AmountField(null=True, verbose_name="Shipping cost", default=0)

    tax_cost = AmountField(null=True, verbose_name="Tax cost", default=0)

    objects = ProductManager()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        db_table = "forj_product"
        abstract = False

    def __str__(self):
        return "{}: {}".format(self.name, self.reference)

    def handle_reference(self, reference):
        if self.reference == reference:
            return True

        criteria_set = CriteriaSet.from_reference(reference)

        if criteria_set.is_empty() and self.criteria_set.is_empty():
            return False

        if criteria_set in self.criteria_set and len(criteria_set) == len(
            self.criteria_set
        ):
            if not self.condition:
                return True

            cond = self.condition

            for criteria in criteria_set:
                cond = cond.replace(criteria.name, criteria.value)

            if expr(cond):
                return True

        return False

    def get_price(self, reference):
        if not self.formula:
            return self.price

        formula = self.formula

        for criteria in CriteriaSet.from_reference(reference):
            formula = formula.replace(criteria.name, criteria.value)

        return round(expr(formula), 2)

    @cached_property
    def criteria_set(self):
        return CriteriaSet.from_reference(self.reference)

    def format_description(self, reference):
        if not self.description:
            return None

        description = self.description

        for criteria in CriteriaSet.from_reference(reference):
            description = description.replace("{%s}" % criteria.name, criteria.value)

        return description

    @property
    def serialized_data(self):
        return {
            "id": self.pk,
            "price": self.price,
            "shipping_cost": self.shipping_cost,
            "description": self.description,
            "name": self.name,
            "currency": self.currency,
        }

src/forj/forms/fields.py
from django import forms


class AmountField(forms.FloatField):
    def prepare_value(self, value):
        if value:
            value = float(value) / 100.0

        return super().prepare_value(value)

    def to_python(self, value):
        value = super().to_python(value)

        if value:
            return int(value * 100.0)

        return value

src/forj/forms/widgets.py
from django.forms.widgets import ChoiceWidget


class Radio(ChoiceWidget):
    input_type = "radio"
    template_name = "forj/forms/widgets/radio.html"
    option_template_name = "forj/forms/widgets/radio_option.html"

src/forj/web/frontend/forms/registration.py
from django import forms

from .address import RequiredAddressForm, OptionalAddressForm


class RegistrationForm(forms.Form):
    diff = forms.BooleanField(required=False)
    cgu = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        self._order = kwargs.pop("order", None)

        country = kwargs.pop("country", None)

        super().__init__(*args, **kwargs)

        self.shipping_address = None
        self.billing_address = None

        if self._order:
            if self._order.shipping_address_id:
                self.shipping_address = self._order.shipping_address

            if self._order.billing_address_id:
                self.billing_address = self._order.billing_address
                self.fields["diff"].initial = True

        if country is not None:
            self.initial = {
                "shipping-address-country": country,
                "billing-address-country": country,
            }

            if self.data:
                data = self.data.copy()

                data["shipping-address-country"] = country
                data["billing-address-country"] = country

                self.data = data

        self.forms = {}

        self.forms["shipping_address"] = RequiredAddressForm(
            self.data or None,
            self.files or None,
            initial=self.initial,
            instance=self.shipping_address,
            prefix="shipping-address",
        )

        billing_address_form_class = OptionalAddressForm

        if self.data.get("diff"):
            billing_address_form_class = RequiredAddressForm

        self.forms["billing_address"] = billing_address_form_class(
            self.data or None,
            self.files or None,
            instance=self.billing_address,
            initial=self.initial,
            prefix="billing-address",
        )

        self.forms["billing_address"].fields["phone_number"].required = False

    def is_valid(self):
        return (
            all([form.is_valid() for form in self.forms.values()]) & super().is_valid()
        )

    def save(self, order, *args, **kwargs):
        order.shipping_address = self.forms["shipping_address"].save()

        if self.cleaned_data.get("diff"):
            order.billing_address = self.forms["billing_address"].save()
        else:
            order.billing_address = None

        order.save(update_fields=("shipping_address", "billing_address",))

        return order

src/forj/web/frontend/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import (
    HttpResponseBadRequest,
    JsonResponse,
    HttpResponsePermanentRedirect,
)
from django.views import generic
from django.conf import settings
from django.db import transaction
from django.utils.functional import cached_property
from django.urls import NoReverseMatch
from django.utils.module_loading import import_string
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.utils import timezone

from forj.web.frontend.forms import RegistrationForm
from forj.models import Order, ContentNode, Page
from forj.cart import Cart
from forj import exceptions
from forj.encoders import JSONEncoder
from forj.payment import backend


headers = (
    "HTTP_HOST",
    "REMOTE_ADDR",
    "HTTP_X_FORWARDED_FOR",
    "HTTP_X_FORWARDED_PROTO",
    "HTTP_X_FORWARDED_PROTOCOL",
    "HTTP_ACCEPT_LANGUAGE",
    "QUERY_STRING",
    "X-Real-Ip",
)


class PageDetailView(generic.DetailView):
    template_name = "forj/page/detail.html"
    model = Page
    context_object_name = "page"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = "page"

        return context

    def render_to_response(self, context):
        if self.object.slug != self.kwargs["slug"]:
            return HttpResponsePermanentRedirect(self.object.get_absolute_url())

        return super().render_to_response(context)


@csrf_exempt
def healthcheck(request):
    user = getattr(request, "user", None)

    results = {header: request.META.get(header) for header in headers}

    results["GET"] = request.GET
    results["POST"] = request.POST
    results["USER"] = "{}".format(user or "")
    results["HOST"] = request.get_host()
    results["IS_SECURE"] = request.is_secure()
    results["IS_AJAX"] = request.is_ajax()

    release_tag = getattr(settings, "RELEASE_TAG", None)

    version = getattr(settings, "PROJECT_VERSION", None)

    uptime = getattr(settings, "PROJECT_UPTIME", None)

    if version is not None and "." in version:
        version = import_string(version)

    results["sha"] = release_tag
    results["tznow"] = timezone.now()
    results["now"] = datetime.now()
    results["version"] = version
    results["uptime"] = uptime
    results["uptime_since"] = naturaltime(uptime)

    return JsonResponse(results)


def home(request, template_name="forj/home.html", **extra):
    extra["nodes"] = {
        "carousel_top": ContentNode.objects.type(
            ContentNode.TYPE_CHOICES.HOME_CAROUSEL_TOP
        ),
        "carousel_bottom": ContentNode.objects.type(
            ContentNode.TYPE_CHOICES.HOME_CAROUSEL_BOTTOM
        ),
        "portrait": ContentNode.objects.type(ContentNode.TYPE_CHOICES.HOME_PORTRAIT),
    }

    return render(request, template_name, extra)


def collection(request, template_name="forj/collection.html", **extra):
    extra["nodes"] = {
        "carousel": ContentNode.objects.type(
            ContentNode.TYPE_CHOICES.COLLECTION_CAROUSEL
        ),
        "selection": ContentNode.objects.type(
            ContentNode.TYPE_CHOICES.COLLECTION_SELECTION
        ),
    }

    return render(request, template_name, extra)


class CheckoutMixin(object):
    @cached_property
    def cart(self):
        return Cart.from_request(self.request)

    @cached_property
    def order(self):
        reference = self.kwargs.get("reference")

        if reference:
            return Order.objects.filter(reference=reference).first()

        return None


class CheckoutView(CheckoutMixin, generic.FormView):
    template_name = "forj/checkout/home.html"
    form_class = RegistrationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart"] = self.cart

        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["country"] = settings.DEFAULT_COUNTRY
        kwargs["order"] = self.order

        return kwargs

    def dispatch(self, *args, **kwargs):
        if not self.cart:
            return redirect("home")

        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        with transaction.atomic():
            self.order = self.cart.save(
                order=self.order,
                defaults={
                    "shipping_address": form.shipping_address,
                    "billing_address": form.billing_address,
                },
            )

            order = form.save(self.order)

            self.request.session["_order_id"] = order.pk

        return super().form_valid(form)

    def get_success_url(self):
        return self.order.get_payment_url()


class OrderView(generic.DetailView):
    slug_field = "reference"
    context_object_name = "order"
    slug_url_kwarg = "reference"

    def get_queryset(self):
        return Order.objects.all()


class PaymentView(OrderView):
    template_name = "forj/checkout/payment.html"

    def get(self, request, *args, **kwargs):
        order = self.get_object()

        if order.is_status_succeeded():
            return redirect(order.get_success_url())

        order = backend.handle_order(order)

        if order.redirect_url:
            return redirect(order.redirect_url)

        if order.is_status_succeeded():
            return redirect(order.get_success_url())

        return super().get(request, *args, **kwargs)


class SuccessView(OrderView):
    template_name = "forj/checkout/success.html"

    def get_queryset(self):
        return super().get_queryset().filter(status=Order.STATUS_CHOICES.SUCCEEDED)


class InvoiceView(SuccessView):
    template_name = "forj/checkout/invoice.html"


@csrf_exempt
def cart(request):
    params = getattr(request, request.method)

    action = params.get("action")

    cart = Cart.from_request(request)
    if cart is None:
        cart = Cart()

    reference_list = params.getlist("reference")

    if action is not None:
        if action == "detail":
            if reference_list is None:
                return HttpResponseBadRequest("Missing `reference` parameter")

            cart = Cart()
            for reference in reference_list:
                try:
                    cart.add_product(reference, params.get("quantity") or 1)
                except exceptions.InvalidProductRef as e:
                    return HttpResponseBadRequest(e)
            return JsonResponse(cart.response, encoder=JSONEncoder)
        elif action in ("add", "remove"):
            if reference_list is None:
                return HttpResponseBadRequest("Missing `reference` parameter")

            try:
                if action == "add":
                    for reference in reference_list:
                        cart.add_product(reference, params.get("quantity") or 1)
                elif action == "remove":
                    for reference in reference_list:
                        cart.remove_product(reference)
            except exceptions.InvalidProductRef as e:
                return HttpResponseBadRequest(e)
        elif action == "flush":
            cart = Cart.flush(request)

        cart.to_request(request)

    next_value = params.get("next")
    if next_value:
        try:
            return redirect(next_value)
        except NoReverseMatch:
            return HttpResponseBadRequest()

    return JsonResponse(cart.response, encoder=JSONEncoder)

src/forj/templates/forj/checkout/_cart.html
<section class="basket-container">
    {% if cart %}
        <div class="article-container">
            {% for item in cart.get_items() %}
                {% with product=item.product %}
                    <div class="article">
                        {% if not product.description %}
                            <div class="detail">Nom : {{ item.product.name }}</div>
                            <div class="detail">Dimensions : {{ item.reference }}</div>
                        {% else %}
                            {% for line in product.format_description(item.reference).splitlines() %}
                                <div class="detail">{{ line }}</div>
                            {% endfor %}
                        {% endif %}
                        <div class="detail">Quantité : {{ item.quantity }}</div>
                        <p class="index" style="display: none;">0</p>
                        {% if enable_delete %}
                            <p class="delete">
                                <a href="{{ url('cart') }}" data-reference="{{ item.reference }}" data-action="remove">
                                    SUPPRIMER
                                </a>
                            </p>
                        {% endif %}
                        <p class="price">{{ item.total|amountformat(AMOUNT_PRECISION) }} {{ CURRENCY_DISPLAY }}</p>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
    {% endif %}
    <div class="infos">
        <h2>Prix de livraison inclus</h2>
        <p class="legal">En France métropolitaine sous 5 semaines. Une fois votre commande validée, nous vous appelons sous une semaine pour choisir votre date de livraison</p>

        <div class="separation"></div>

        {% if cart %}
            <div class="price-container">
                <p>Total TTC</p>
                <p id="total" class="price"><span id="total-container">{{ cart.total|amountformat }}</span> {{ CURRENCY_DISPLAY }}</p>
            </div>
            <div class="separation"></div>
        {% endif %}


        {% if enable_cgu %}
            <div class="check-cgu-container">
                {{ form.cgu }}
                <label for="{{ form.cgu.id_for_label }}"><span>J’accepte les <a class="cgu-basket-launcher" target="_blank" href="{{ url('terms') }}">conditions générales de ventes</a></span></label>
            </div>
        {% endif %}
    </div>

    <div class="processing-container">
        <input type="submit" name="" value="En cours de traitement..."/>
    </div>

    <div class="submit-container">
        <div class="button arrow right submit-arrow"><span></span></div>
        <input type="submit" name="" value="Valider et payer"/>
    </div>
</section>

src/forj/templates/forj/checkout/base.html
{% extends "forj/base.html" %}

{% block body %}
    <div class="main-wrapper">
        <nav>
            <a href="{{ url("home") }}" class="logo">Forj</a>
            {% block nav %}

            {% endblock %}
        </nav>
    </div>

    <div class="main-wrapper">
        <main>
            {% if messages %}
                <ul id="messages-container">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if form and form.errors %}
                {% with non_field_errors=form.non_field_errors() %}
                    {% if non_field_errors %}
                        {% for error in non_field_errors %}
                            <p class="error-label active">{{ error }}</p>
                        {% endfor %}
                    {% else %}
                        <p class="error-label active">Certains champs sont incorrects ou incomplets</p>
                    {% endif %}
                {% endwith %}
            {% endif %}
            {% block main %}

            {% endblock %}
        </main>
    </div>

    {% block footer %}
        {% include "forj/_footer.html" %}
    {% endblock %}
{% endblock %} 

src/forj/templates/forj/checkout/home.html
{% extends "forj/checkout/base.html" %}

{% import 'forj/forms.html' as forms %}

{% block title %}Mon panier{% endblock %}
{% block body_class %}checkout{% endblock %}

{% block nav %}
    <ul>
        <li><a class="" href="{{ url("home") }}">Retourner à mes achats</a></li>
    </ul>
{% endblock %}

{% block main %}
    <form class="main" id="checkout-form" action="" method="post" novalidate>
        {% csrf_token %}

        <h1>Mes informations</h1>
        <p style="margin-bottom: 10px">Si vous avez des questions, appelez nous au {{ FORJ_PHONE_NUMBER }}</p>
        <h2>(tous les champs sont obligatoires)</h2>

        {{ form.forms.shipping_address.type }}

        <div class="inputs-container">
            {{ forms.input(form.forms.shipping_address.first_name, label="Prénom") }}

            {{ forms.input(form.forms.shipping_address.last_name, label="Nom") }}

            {{ forms.input(form.forms.shipping_address.business_name, label="Nom d'entreprise") }}

            {{ forms.input(form.forms.shipping_address.email, label="Adresse mail") }}

            {{ forms.input(form.forms.shipping_address.phone_number, label="Téléphone") }}
        </div>

        <div class="facturation-container">
            {{ form.diff }}
            <label for="id_diff"><span>Mon adresse de livraison est différente <br>de celle de facturation</span></label>
        </div>

        <div class="separation"></div>
        <h1>Votre adresse (France métropolitaine)</h1>
        <h2>(tous les champs sont obligatoires)</h2>

        <div class="inputs-container">
            {{ forms.input(form.forms.shipping_address.line1, label="Voie, rue") }}
            {{ forms.input(form.forms.shipping_address.postal_code, label="Code postal") }}
            {{ forms.input(form.forms.shipping_address.city, label="Ville") }}
        </div>

        <div class="separation"></div>

        <div style="display: none" id="billing-wrapper">
            <h1>Adresse de facturation</h1>
            <h2>(tous les champs sont obligatoires)</h2>
            {{ form.forms.billing_address.type }}

            <div class="inputs-container">
                {{ forms.input(form.forms.billing_address.first_name, label="Prénom") }}
                {{ forms.input(form.forms.billing_address.last_name, label="Nom") }}
                {{ forms.input(form.forms.billing_address.email, label="Adresse mail") }}
                {{ forms.input(form.forms.billing_address.business_name, label="Nom d'entreprise") }}
                {{ forms.input(form.forms.billing_address.line1, label="Voie, rue") }}
                {{ forms.input(form.forms.billing_address.postal_code, label="Code postal") }}
                {{ forms.input(form.forms.billing_address.city, label="Ville") }}
            </div>
            <div class="separation"></div>
        </div>

        <div class="comments-wrapper">
            <h1>Informations complémentaires</h1>
            <h2>(difficultés d’accès, codes d’entrée, interphone...)</h2>

            {{ forms.textarea(form.forms.shipping_address.line2) }}
        </div>

        {% with enable_cgu=True, enable_delete=True %}
            {% include "forj/checkout/_cart.html" %}
        {% endwith %}
    </form>
{% endblock %} 

{% block extend_js %}
    <script type="text/javascript" src="{{ static('site/build/javascript/checkout.js') }}"></script>
{% endblock %}

src/forj/templates/forj/checkout/invoice.html
{% extends "forj/base.html" %}

{% block title %}Ma facture{% endblock %}

{% block body_class %}facture{% endblock %}

{% block body %}
    <header>
        <img width="120" src="{{ static("site/build/assets/images/Logo_square.svg") }}" alt="">
        <div class="text-content">
            <h2>Forj, table sur-mesure</h2>
            <p>{{ order.created_at|date("d/m/Y") }}</p>
            <p>Facture n°{{ order.invoice_number }}</p>
        </div>
    </header>

    <h1>Adresses</h1>

    {% if order.shipping_address_id %}
        <div class="address">
            <h3>Livraison</h3>
            <p>{{ order.shipping_address.formatted|linebreaksbr }}</p>
        </div>
    {% endif %}

    {% if order.billing_address_id %}
        <div class="address">
            <h3>Facturation</h3>
            <p>{{ order.billing_address.formatted|linebreaksbr }}</p>
        </div>
    {% endif %}

    <table class="main">
        <tr>
            <th>Produit/référence</th>
            <th width="15%">Qté</th>
            <th width="25%">Prix</th>
        </tr>

        {% for item in order.items.all() %}
            <tr>
                <td>{{ item.product_reference }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.amount|amountformat }} {{ order.get_currency_display() }} HC</td>
            </tr>
        {% endfor %}
    </table>

    <div class="price">
        <table class="price">
            <tr>
                <th>TVA 19,6%</th>
                <th>{{ order.tax_cost|amountformat }} {{ order.get_currency_display() }}</th>
            </tr>
            <tr>
                <td>Total TTC</td>
                <td>{{ order.total|amountformat }} {{ order.get_currency_display() }}</td>
            </tr>
        </table>
    </div>

    <p class="cgv">
        Forj est une marque déposée de la société B concept, 16 rue Saint Just, Noisy le Sec
        <br> contact : 0678458812 forj.info@gmail.com
    </p>
{% endblock %}

src/forj/templates/forj/checkout/payment.html
{% extends "forj/checkout/base.html" %}

{% block title %}Paiement{% endblock %}
{% block body_class %}payment{% endblock %}

{% block nav %}
    <ul>
        <li><a class="" href="{{ order.get_checkout_url() }}">Retourner à mes informations</a></li>
    </ul>
{% endblock %}

{% block extend_js %}
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        window.FJ = {
            stripe_session_id: '{{ order.stripe_session_id }}',
            stripe_publishable_key: '{{ STRIPE_PUBLISHABLE_KEY }}'
        }
    </script>
    <script type="text/javascript" src="{{ static('site/build/javascript/payment.js') }}"></script>
{% endblock %}

{% block main %}
    <h1 class="loading-dots">En cours de traitement</h1>
    <p>Vous allez être redirigé vers notre prestataire de paiement.</p>
{% endblock %}

src/forj/templates/forj/checkout/success.html
{% extends "forj/base.html" %}

{% block body_class %}success{% endblock %}

{% block title %}Félicitation{% endblock %}

{% block body %}
    <nav>
        <a href="/" class="logo">Forj</a>
    </nav>

    <div class="{% block wrapper_class %}wrapper wrapper--sticky{% endblock %}">
        {% block success_content %}
            <h1>Bravo et merci !</h1>
            <p>Votre commande est traitée par notre équipe, un mail de confirmation va vous être envoyé. Nous vous contacterons d'ici une semaine pour fixer une date de livraison. Si vous le souhaitez vous pouvez télécharger <a href="{{ order.get_invoice_url() }}">votre facture ici</a>.</p>
        {% endblock %}

        <div class="links">
            <a class="button inverted" href="/">RETOURNER AU SITE</a>
            <span class="intro-socials">Ou suivez-nous sur</span>
            <div class="socials-wrapper">
                <a href="{{ FORJ_FACEBOOK_URL }}" class="button facebook">
                    <i class="demo-icon icon-facebook"></i>
                    </a>&nbsp;<a href="{{ FORJ_INSTAGRAM_URL }}" class="button instagram">
                    <i class="demo-icon icon-instagram"></i>
                </a>
            </div>
        </div>
    </div>
{% endblock %}